name: Java CI with Trivy

on:
  push:
    branches: ["main"]

jobs:
  maven:
    name: Build (Maven)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B -DskipTests=false compile

      - name: Upload build artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-target
          path: target/**

  security-check:
    name: Security scans (Trivy + Gitleaks)
    runs-on: ubuntu-latest
    needs: maven

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release ca-certificates curl jq

      - name: Install Trivy (Aqua Security)
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      - name: Trivy FS scan (JSON + table)
        run: |
          trivy fs --format json -o trivy-fs-report.json .
          trivy fs --format table -o trivy-fs-report.txt .
        # Fail the job on high/critical findings if you want:
        # run: trivy fs --exit-code 1 --severity CRITICAL,HIGH --format json -o trivy-fs-report.json .

      - name: Upload Trivy reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-fs-report.json
            trivy-fs-report.tx
